name: CI / Deploy to Tencent Cloud

on:
  push:
    branches: [main, develop]

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    env:
      # Default target path on remote server — change if your nginx serves a different folder
      TARGET_PATH: /var/www/nihaozheyang

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Copy build artifacts to remote server (SCP)
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          # upload all files under dist to a temporary folder on the server
          source: "dist/**"
          target: "/tmp/nihaozheyang_build"

      - name: Deploy on remote server and reload nginx
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo mkdir -p ${{ env.TARGET_PATH }}
            sudo rm -rf ${{ env.TARGET_PATH }}/*
            sudo cp -r /tmp/nihaozheyang_build/* ${{ env.TARGET_PATH }}/
            # reload nginx (try systemctl first, fallback to nginx -s reload)
            if command -v systemctl >/dev/null 2>&1; then
              sudo systemctl reload nginx || sudo systemctl restart nginx
            else
              sudo nginx -s reload || true
            fi
            sudo rm -rf /tmp/nihaozheyang_build || true
